//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrelloKubra.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GorevDurumlari
    {
        public int GorevDurumId { get; set; }
        public Nullable<int> GorevId { get; set; }
        public Nullable<int> DurumId { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> GorevDurumTarihi { get; set; }
        public string Yapilacakis1 { get; set; }
        public string Yapilacakis2 { get; set; }
        public string Yapilacakis3 { get; set; }
        public string Yapilacakis4 { get; set; }
    
        public virtual tbl_Durum tbl_Durum { get; set; }
        public virtual tbl_Gorevler tbl_Gorevler { get; set; }
        public virtual tbl_Kullanicilar tbl_Kullanicilar { get; set; }
    }
}
