//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrelloKubra.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Gorevler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Gorevler()
        {
            this.tbl_GorevDurumlari = new HashSet<tbl_GorevDurumlari>();
        }
    
        public int GorevId { get; set; }
        public string GorevAdi { get; set; }
        public string Aciklama { get; set; }
        public string Notlar { get; set; }
        public Nullable<System.DateTime> GorevTarihi { get; set; }
        public Nullable<System.DateTime> TahminiTarih { get; set; }
        public Nullable<System.DateTime> GerceklesenTarih { get; set; }
        public Nullable<int> DurumId { get; set; }
    
        public virtual tbl_Durum tbl_Durum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_GorevDurumlari> tbl_GorevDurumlari { get; set; }
    }
}
